version: '3.4'

services:
  mediacontrollerbackendservices:
    image: ${DOCKER_REGISTRY-}mediacontrollerbackendservices
    build:
      context: ./MediaControllerBackendServices
      dockerfile: Dockerfile
    environment:
     - NETATMO_CLIENT_SECRET
     - NETATMO_CLIENT
     - NETATMO_USER
     - NETATMO_PASSWORD
     - NETATMO_DEVICE
     - MQTT_SERVER
  raspifrontendangular:
    image: ${DOCKER_REGISTRY-}raspifrontendangular
    build:
      context: ./RaspiFrontendAngular
      dockerfile: Dockerfile
    depends_on: 
     - mediacontrollerbackendservices
    ports: 
     - 80:80
  fluentd:
    build: ./fluentd
    volumes:
        - ./fluentd/conf:/fluentd/etc
    ports:
      - "9880:9880"
      - "9880:9880/udp"