version: '3.4'

services:
  raspifrontendangular:
    image: 80er/netatmoweatherstationdisplay:LATEST
    restart: always
    ports: 
     - 80:80
  # we have to reactivate that again... 
  # raumserver:
  #   image: ${DOKCER_REGISTRY-}raumserver
  #   build:
  #     context: ./docker-node-raumserver
  #     dockerfile: Dockerfile
  #   network_mode: host
  #   restart: always
  #   ports:
  #     - 3535:3535
  #     - 3536:3536