version: '3.4'

services:
  mediacontrollerbackendservices:
    image: ${DOCKER_REGISTRY-}mediacontrollerbackendservices
    build:
      context: ./MediaControllerBackendServices
      dockerfile: Dockerfile
    environment:
     - NETATMO_CLIENT_SECRET
     - NETATMO_CLIENT
     - NETATMO_USER
     - NETATMO_PASSWORD
     - NETATMO_DEVICE
     - MQTT_SERVER
  raspifrontendangular:
    image: ${DOCKER_REGISTRY-}raspifrontendangular
    build:
      context: ./RaspiFrontendAngular
      dockerfile: Dockerfile
    depends_on: 
     - mediacontrollerbackendservices
    ports: 
     - 80:80
  fluentd:
    image:  ${DOCKER_REGISTRY-}fluentd
    build: 
      context: ./fluentd
      dockerfile: Dockerfile
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "9880:9880"
      - "9880:9880/udp"
  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.4.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"