version: '3.4'

services:
  mediacontrollerbackendservices:
    image: ${DOCKER_REGISTRY-}mediacontrollerbackendservices
    build:
      context: ./MediaControllerBackendServices
      dockerfile: Dockerfile
    environment:
     - NETATMO_CLIENT_SECRET
     - NETATMO_CLIENT
     - NETATMO_USER
     - NETATMO_PASSWORD
     - NETATMO_DEVICE
     - MQTT_SERVER
    ports:
     - 9001:9001
  raspifrontendangular:
    image: ${DOCKER_REGISTRY-}raspifrontendangular
    build:
      context: ./RaspiFrontendAngular
      dockerfile: Dockerfile
    depends_on: 
     - mediacontrollerbackendservices
    ports: 
     - 80:80